version: '3.2'

services:
  app:
    build: .
    restart: unless-stopped
    container_name: app
    ports:
      - "8000:8000"
  
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: crawler
    ports:
      - "5432:5432"
